# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Contour
                                 A QGIS plugin
 Generates contours from point layer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-04-24
        copyright            : (C) 2018 by Chris Crook
        email                : ccrook@linz.govt.nz
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = "Chris Crook"
__date__ = "2018-04-24"
__copyright__ = "(C) 2018 by Chris Crook"


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ContourPlugin class from file ContourPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ContourPlugin import ContourPlugin

    return ContourPlugin(iface)
