# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ContourDialogUi.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ContourDialog(object):
    def setupUi(self, ContourDialog):
        ContourDialog.setObjectName("ContourDialog")
        ContourDialog.setWindowModality(QtCore.Qt.NonModal)
        ContourDialog.resize(658, 746)
        ContourDialog.setSizeGripEnabled(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(ContourDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(ContourDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.uDataField = QgsFieldExpressionWidget(self.groupBox_2)
        self.uDataField.setObjectName("uDataField")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.uDataField)
        self.uSelectedOnly = QtWidgets.QCheckBox(self.groupBox_2)
        self.uSelectedOnly.setObjectName("uSelectedOnly")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.uSelectedOnly)
        self.uSourceLayer = QgsMapLayerComboBox(self.groupBox_2)
        self.uSourceLayer.setObjectName("uSourceLayer")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.uSourceLayer)
        self.gridLayout.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.uRemoveDuplicates = QtWidgets.QCheckBox(self.groupBox_2)
        self.uRemoveDuplicates.setText("")
        self.uRemoveDuplicates.setObjectName("uRemoveDuplicates")
        self.horizontalLayout.addWidget(self.uRemoveDuplicates)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.uDuplicateTolerance = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.uDuplicateTolerance.setDecimals(3)
        self.uDuplicateTolerance.setMinimum(0.001)
        self.uDuplicateTolerance.setMaximum(99999.999)
        self.uDuplicateTolerance.setSingleStep(0.001)
        self.uDuplicateTolerance.setProperty("value", 0.001)
        self.uDuplicateTolerance.setObjectName("uDuplicateTolerance")
        self.horizontalLayout.addWidget(self.uDuplicateTolerance)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 7, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.uUseGridLabel = QtWidgets.QLabel(self.groupBox_2)
        self.uUseGridLabel.setEnabled(True)
        self.uUseGridLabel.setObjectName("uUseGridLabel")
        self.horizontalLayout_3.addWidget(self.uUseGridLabel)
        self.uUseGrid = QtWidgets.QCheckBox(self.groupBox_2)
        self.uUseGrid.setText("")
        self.uUseGrid.setObjectName("uUseGrid")
        self.horizontalLayout_3.addWidget(self.uUseGrid)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.uLayerDescription = QtWidgets.QLabel(self.groupBox_2)
        self.uLayerDescription.setText("")
        self.uLayerDescription.setObjectName("uLayerDescription")
        self.gridLayout.addWidget(self.uLayerDescription, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(ContourDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.uLinesContours = QtWidgets.QRadioButton(self.groupBox)
        self.uLinesContours.setObjectName("uLinesContours")
        self.horizontalLayout_7.addWidget(self.uLinesContours)
        self.uFilledContours = QtWidgets.QRadioButton(self.groupBox)
        self.uFilledContours.setObjectName("uFilledContours")
        self.horizontalLayout_7.addWidget(self.uFilledContours)
        self.uBoth = QtWidgets.QRadioButton(self.groupBox)
        self.uBoth.setObjectName("uBoth")
        self.horizontalLayout_7.addWidget(self.uBoth)
        self.uLayerContours = QtWidgets.QRadioButton(self.groupBox)
        self.uLayerContours.setObjectName("uLayerContours")
        self.horizontalLayout_7.addWidget(self.uLayerContours)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 0, 1, 3)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 10, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.uNContour = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uNContour.sizePolicy().hasHeightForWidth())
        self.uNContour.setSizePolicy(sizePolicy)
        self.uNContour.setMinimum(1)
        self.uNContour.setMaximum(9999)
        self.uNContour.setProperty("value", 10)
        self.uNContour.setObjectName("uNContour")
        self.gridLayout_2.addWidget(self.uNContour, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 8, 0, 1, 1)
        self.uExtend = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uExtend.sizePolicy().hasHeightForWidth())
        self.uExtend.setSizePolicy(sizePolicy)
        self.uExtend.setObjectName("uExtend")
        self.gridLayout_2.addWidget(self.uExtend, 8, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.uSetMaximum = QtWidgets.QCheckBox(self.groupBox)
        self.uSetMaximum.setObjectName("uSetMaximum")
        self.horizontalLayout_6.addWidget(self.uSetMaximum)
        self.uMaxContour = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uMaxContour.sizePolicy().hasHeightForWidth())
        self.uMaxContour.setSizePolicy(sizePolicy)
        self.uMaxContour.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.uMaxContour.setDecimals(4)
        self.uMaxContour.setMinimum(-999999999.0)
        self.uMaxContour.setMaximum(999999999.0)
        self.uMaxContour.setObjectName("uMaxContour")
        self.horizontalLayout_6.addWidget(self.uMaxContour)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 7, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.uMethod = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uMethod.sizePolicy().hasHeightForWidth())
        self.uMethod.setSizePolicy(sizePolicy)
        self.uMethod.setObjectName("uMethod")
        self.gridLayout_2.addWidget(self.uMethod, 1, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.uSetMinimum = QtWidgets.QCheckBox(self.groupBox)
        self.uSetMinimum.setObjectName("uSetMinimum")
        self.horizontalLayout_5.addWidget(self.uSetMinimum)
        self.uMinContour = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uMinContour.sizePolicy().hasHeightForWidth())
        self.uMinContour.setSizePolicy(sizePolicy)
        self.uMinContour.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.uMinContour.setDecimals(4)
        self.uMinContour.setMinimum(-999999999.0)
        self.uMinContour.setMaximum(999999999.0)
        self.uMinContour.setObjectName("uMinContour")
        self.horizontalLayout_5.addWidget(self.uMinContour)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 5, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 7, 0, 1, 1)
        self.uContourInterval = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uContourInterval.sizePolicy().hasHeightForWidth())
        self.uContourInterval.setSizePolicy(sizePolicy)
        self.uContourInterval.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.uContourInterval.setDecimals(4)
        self.uContourInterval.setMinimum(-999999999.0)
        self.uContourInterval.setMaximum(999999999.0)
        self.uContourInterval.setObjectName("uContourInterval")
        self.gridLayout_2.addWidget(self.uContourInterval, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 2, 0, 1, 1)
        self.uLevelsList = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uLevelsList.sizePolicy().hasHeightForWidth())
        self.uLevelsList.setSizePolicy(sizePolicy)
        self.uLevelsList.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.uLevelsList.setObjectName("uLevelsList")
        self.gridLayout_2.addWidget(self.uLevelsList, 1, 2, 10, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(ContourDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, -1, -1, 6)
        self.formLayout.setObjectName("formLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.uOutputName = QtWidgets.QLineEdit(self.groupBox_3)
        self.uOutputName.setObjectName("uOutputName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.uOutputName)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uPrecision = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uPrecision.sizePolicy().hasHeightForWidth())
        self.uPrecision.setSizePolicy(sizePolicy)
        self.uPrecision.setMinimum(-1)
        self.uPrecision.setMaximum(10)
        self.uPrecision.setProperty("value", 4)
        self.uPrecision.setObjectName("uPrecision")
        self.horizontalLayout_2.addWidget(self.uPrecision)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.uTrimZeros = QtWidgets.QCheckBox(self.groupBox_3)
        self.uTrimZeros.setText("")
        self.uTrimZeros.setObjectName("uTrimZeros")
        self.horizontalLayout_2.addWidget(self.uTrimZeros)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.uLabelUnits = QtWidgets.QLineEdit(self.groupBox_3)
        self.uLabelUnits.setObjectName("uLabelUnits")
        self.horizontalLayout_2.addWidget(self.uLabelUnits)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.uApplyColors = QtWidgets.QCheckBox(self.groupBox_3)
        self.uApplyColors.setText("")
        self.uApplyColors.setObjectName("uApplyColors")
        self.horizontalLayout_4.addWidget(self.uApplyColors)
        self.uColorRamp = QgsColorRampButton(self.groupBox_3)
        self.uColorRamp.setObjectName("uColorRamp")
        self.horizontalLayout_4.addWidget(self.uColorRamp)
        self.uReverseRamp = QtWidgets.QCheckBox(self.groupBox_3)
        self.uReverseRamp.setObjectName("uReverseRamp")
        self.horizontalLayout_4.addWidget(self.uReverseRamp)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.horizontalLayout_4.setStretch(1, 1)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.gridLayout_4.addLayout(self.formLayout, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.uMessageBar = QgsMessageBar(ContourDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uMessageBar.sizePolicy().hasHeightForWidth())
        self.uMessageBar.setSizePolicy(sizePolicy)
        self.uMessageBar.setMinimumSize(QtCore.QSize(0, 27))
        self.uMessageBar.setObjectName("uMessageBar")
        self.verticalLayout.addWidget(self.uMessageBar)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.progressBar = QtWidgets.QProgressBar(ContourDialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_8.addWidget(self.progressBar)
        self.uHelpButton = QtWidgets.QPushButton(ContourDialog)
        self.uHelpButton.setAutoDefault(False)
        self.uHelpButton.setObjectName("uHelpButton")
        self.horizontalLayout_8.addWidget(self.uHelpButton)
        self.uAddButton = QtWidgets.QPushButton(ContourDialog)
        self.uAddButton.setObjectName("uAddButton")
        self.horizontalLayout_8.addWidget(self.uAddButton)
        self.uCloseButton = QtWidgets.QPushButton(ContourDialog)
        self.uCloseButton.setObjectName("uCloseButton")
        self.horizontalLayout_8.addWidget(self.uCloseButton)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout.setStretch(1, 1)
        self.label_3.setBuddy(self.uSourceLayer)
        self.label_4.setBuddy(self.uDataField)
        self.label_2.setBuddy(self.uRemoveDuplicates)
        self.label_11.setBuddy(self.uDuplicateTolerance)
        self.uUseGridLabel.setBuddy(self.uUseGrid)
        self.label_5.setBuddy(self.uSetMinimum)
        self.label.setBuddy(self.uNContour)
        self.label_10.setBuddy(self.uExtend)
        self.label_7.setBuddy(self.uMethod)
        self.label_6.setBuddy(self.uSetMaximum)
        self.label_15.setBuddy(self.uContourInterval)
        self.label_8.setBuddy(self.uOutputName)
        self.label_14.setBuddy(self.uTrimZeros)
        self.label_12.setBuddy(self.uLabelUnits)
        self.label_9.setBuddy(self.uPrecision)
        self.label_13.setBuddy(self.uApplyColors)

        self.retranslateUi(ContourDialog)
        QtCore.QMetaObject.connectSlotsByName(ContourDialog)
        ContourDialog.setTabOrder(self.uSourceLayer, self.uSelectedOnly)
        ContourDialog.setTabOrder(self.uSelectedOnly, self.uRemoveDuplicates)
        ContourDialog.setTabOrder(self.uRemoveDuplicates, self.uDuplicateTolerance)
        ContourDialog.setTabOrder(self.uDuplicateTolerance, self.uUseGrid)
        ContourDialog.setTabOrder(self.uUseGrid, self.uLinesContours)
        ContourDialog.setTabOrder(self.uLinesContours, self.uFilledContours)
        ContourDialog.setTabOrder(self.uFilledContours, self.uBoth)
        ContourDialog.setTabOrder(self.uBoth, self.uLayerContours)
        ContourDialog.setTabOrder(self.uLayerContours, self.uMethod)
        ContourDialog.setTabOrder(self.uMethod, self.uContourInterval)
        ContourDialog.setTabOrder(self.uContourInterval, self.uNContour)
        ContourDialog.setTabOrder(self.uNContour, self.uSetMinimum)
        ContourDialog.setTabOrder(self.uSetMinimum, self.uMinContour)
        ContourDialog.setTabOrder(self.uMinContour, self.uSetMaximum)
        ContourDialog.setTabOrder(self.uSetMaximum, self.uMaxContour)
        ContourDialog.setTabOrder(self.uMaxContour, self.uExtend)
        ContourDialog.setTabOrder(self.uExtend, self.uLevelsList)
        ContourDialog.setTabOrder(self.uLevelsList, self.uOutputName)
        ContourDialog.setTabOrder(self.uOutputName, self.uPrecision)
        ContourDialog.setTabOrder(self.uPrecision, self.uTrimZeros)
        ContourDialog.setTabOrder(self.uTrimZeros, self.uLabelUnits)
        ContourDialog.setTabOrder(self.uLabelUnits, self.uApplyColors)
        ContourDialog.setTabOrder(self.uApplyColors, self.uColorRamp)
        ContourDialog.setTabOrder(self.uColorRamp, self.uReverseRamp)
        ContourDialog.setTabOrder(self.uReverseRamp, self.uAddButton)
        ContourDialog.setTabOrder(self.uAddButton, self.uCloseButton)

    def retranslateUi(self, ContourDialog):
        _translate = QtCore.QCoreApplication.translate
        ContourDialog.setWindowTitle(_translate("ContourDialog", "Contour"))
        self.groupBox_2.setTitle(_translate("ContourDialog", "Input"))
        self.label_3.setText(_translate("ContourDialog", "Point layer"))
        self.label_4.setText(_translate("ContourDialog", "Data value"))
        self.uSelectedOnly.setText(_translate("ContourDialog", "Use selected points only"))
        self.label_2.setText(_translate("ContourDialog", "Remove duplicate points"))
        self.label_11.setText(_translate("ContourDialog", "Tolerance"))
        self.uUseGridLabel.setText(_translate("ContourDialog", "Use grid based contouring"))
        self.groupBox.setTitle(_translate("ContourDialog", "Contouring"))
        self.uLinesContours.setText(_translate("ContourDialog", "contour lines"))
        self.uFilledContours.setText(_translate("ContourDialog", "filled contours"))
        self.uBoth.setText(_translate("ContourDialog", "both"))
        self.uLayerContours.setText(_translate("ContourDialog", "contour layers"))
        self.label_5.setText(_translate("ContourDialog", "Minimum"))
        self.label.setText(_translate("ContourDialog", "Number"))
        self.uNContour.setStatusTip(_translate("ContourDialog", "Number of levels between min and max value (from data field)"))
        self.label_10.setText(_translate("ContourDialog", "Extend"))
        self.uSetMaximum.setText(_translate("ContourDialog", "Set"))
        self.label_7.setText(_translate("ContourDialog", "Method"))
        self.uSetMinimum.setText(_translate("ContourDialog", "Set"))
        self.label_6.setText(_translate("ContourDialog", "Maximum"))
        self.label_15.setText(_translate("ContourDialog", "Interval"))
        self.groupBox_3.setTitle(_translate("ContourDialog", "Output"))
        self.label_8.setText(_translate("ContourDialog", "Layer name"))
        self.uPrecision.setStatusTip(_translate("ContourDialog", "Number of decimal places shown in labels"))
        self.label_14.setText(_translate("ContourDialog", "Trim zeros"))
        self.label_12.setText(_translate("ContourDialog", "Units"))
        self.label_9.setText(_translate("ContourDialog", "Label precision"))
        self.uReverseRamp.setText(_translate("ContourDialog", "reverse"))
        self.label_13.setText(_translate("ContourDialog", "Apply colours"))
        self.uHelpButton.setText(_translate("ContourDialog", "Help"))
        self.uAddButton.setText(_translate("ContourDialog", "Add"))
        self.uCloseButton.setText(_translate("ContourDialog", "Close"))

from qgis.gui import QgsColorRampButton
from qgis.gui import QgsFieldExpressionWidget
from qgis.gui import QgsMapLayerComboBox
from qgis.gui import QgsMessageBar
