# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frmContour.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ContourDialog(object):
    def setupUi(self, ContourDialog):
        ContourDialog.setObjectName("ContourDialog")
        ContourDialog.setWindowModality(QtCore.Qt.NonModal)
        ContourDialog.resize(484, 653)
        ContourDialog.setSizeGripEnabled(True)
        self.gridLayout_3 = QtWidgets.QGridLayout(ContourDialog)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(ContourDialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.uLayerName = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uLayerName.sizePolicy().hasHeightForWidth())
        self.uLayerName.setSizePolicy(sizePolicy)
        self.uLayerName.setStatusTip("")
        self.uLayerName.setObjectName("uLayerName")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.uLayerName)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.uDataField = gui.QgsFieldExpressionWidget(self.groupBox_2)
        self.uDataField.setObjectName("uDataField")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.uDataField)
        self.uSelectedOnly = QtWidgets.QCheckBox(self.groupBox_2)
        self.uSelectedOnly.setObjectName("uSelectedOnly")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.uSelectedOnly)
        self.gridLayout.addLayout(self.formLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.uThinPoints = QtWidgets.QCheckBox(self.groupBox_2)
        self.uThinPoints.setText("")
        self.uThinPoints.setObjectName("uThinPoints")
        self.horizontalLayout.addWidget(self.uThinPoints)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout.addWidget(self.label_11)
        self.uThinRadius = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.uThinRadius.setDecimals(6)
        self.uThinRadius.setSingleStep(1e-06)
        self.uThinRadius.setObjectName("uThinRadius")
        self.horizontalLayout.addWidget(self.uThinRadius)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 7, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.uUseGridLabel = QtWidgets.QLabel(self.groupBox_2)
        self.uUseGridLabel.setEnabled(True)
        self.uUseGridLabel.setObjectName("uUseGridLabel")
        self.horizontalLayout_3.addWidget(self.uUseGridLabel)
        self.uUseGrid = QtWidgets.QCheckBox(self.groupBox_2)
        self.uUseGrid.setText("")
        self.uUseGrid.setObjectName("uUseGrid")
        self.horizontalLayout_3.addWidget(self.uUseGrid)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.uLayerDescription = QtWidgets.QLabel(self.groupBox_2)
        self.uLayerDescription.setText("")
        self.uLayerDescription.setObjectName("uLayerDescription")
        self.gridLayout.addWidget(self.uLayerDescription, 4, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(ContourDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.uLinesContours = QtWidgets.QRadioButton(self.groupBox)
        self.uLinesContours.setObjectName("uLinesContours")
        self.horizontalLayout_7.addWidget(self.uLinesContours)
        self.uFilledContours = QtWidgets.QRadioButton(self.groupBox)
        self.uFilledContours.setObjectName("uFilledContours")
        self.horizontalLayout_7.addWidget(self.uFilledContours)
        self.uBoth = QtWidgets.QRadioButton(self.groupBox)
        self.uBoth.setObjectName("uBoth")
        self.horizontalLayout_7.addWidget(self.uBoth)
        self.uLayerContours = QtWidgets.QRadioButton(self.groupBox)
        self.uLayerContours.setObjectName("uLayerContours")
        self.horizontalLayout_7.addWidget(self.uLayerContours)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.uLevelsNumber = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uLevelsNumber.sizePolicy().hasHeightForWidth())
        self.uLevelsNumber.setSizePolicy(sizePolicy)
        self.uLevelsNumber.setMinimum(1)
        self.uLevelsNumber.setMaximum(999)
        self.uLevelsNumber.setProperty("value", 10)
        self.uLevelsNumber.setObjectName("uLevelsNumber")
        self.gridLayout_2.addWidget(self.uLevelsNumber, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.uMinContour = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uMinContour.sizePolicy().hasHeightForWidth())
        self.uMinContour.setSizePolicy(sizePolicy)
        self.uMinContour.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.uMinContour.setDecimals(4)
        self.uMinContour.setMinimum(-999999999.0)
        self.uMinContour.setMaximum(999999999.0)
        self.uMinContour.setObjectName("uMinContour")
        self.gridLayout_2.addWidget(self.uMinContour, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 4, 0, 1, 1)
        self.uExtend = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uExtend.sizePolicy().hasHeightForWidth())
        self.uExtend.setSizePolicy(sizePolicy)
        self.uExtend.setObjectName("uExtend")
        self.uExtend.addItem("")
        self.uExtend.addItem("")
        self.uExtend.addItem("")
        self.uExtend.addItem("")
        self.gridLayout_2.addWidget(self.uExtend, 4, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 5, 0, 1, 1)
        self.uMethod = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uMethod.sizePolicy().hasHeightForWidth())
        self.uMethod.setSizePolicy(sizePolicy)
        self.uMethod.setObjectName("uMethod")
        self.uMethod.addItem("")
        self.uMethod.addItem("")
        self.uMethod.addItem("")
        self.gridLayout_2.addWidget(self.uMethod, 5, 1, 1, 1)
        self.uLevelsList = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uLevelsList.sizePolicy().hasHeightForWidth())
        self.uLevelsList.setSizePolicy(sizePolicy)
        self.uLevelsList.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.uLevelsList.setObjectName("uLevelsList")
        self.gridLayout_2.addWidget(self.uLevelsList, 1, 2, 6, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 6, 1, 1, 1)
        self.uMaxContour = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uMaxContour.sizePolicy().hasHeightForWidth())
        self.uMaxContour.setSizePolicy(sizePolicy)
        self.uMaxContour.setLocale(QtCore.QLocale(QtCore.QLocale.C, QtCore.QLocale.AnyCountry))
        self.uMaxContour.setDecimals(4)
        self.uMaxContour.setMinimum(-999999999.0)
        self.uMaxContour.setMaximum(999999999.0)
        self.uMaxContour.setObjectName("uMaxContour")
        self.gridLayout_2.addWidget(self.uMaxContour, 3, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.gridLayout_2.setRowStretch(6, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(ContourDialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_3.addWidget(self.progressBar, 3, 0, 1, 1)
        self.uButtonBox = QtWidgets.QDialogButtonBox(ContourDialog)
        self.uButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.uButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close|QtWidgets.QDialogButtonBox.Help|QtWidgets.QDialogButtonBox.Ok)
        self.uButtonBox.setObjectName("uButtonBox")
        self.gridLayout_3.addWidget(self.uButtonBox, 3, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(ContourDialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, -1, -1, 6)
        self.formLayout.setObjectName("formLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.uOutputName = QtWidgets.QLineEdit(self.groupBox_3)
        self.uOutputName.setObjectName("uOutputName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.uOutputName)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.uPrecision = QtWidgets.QSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.uPrecision.sizePolicy().hasHeightForWidth())
        self.uPrecision.setSizePolicy(sizePolicy)
        self.uPrecision.setMinimum(0)
        self.uPrecision.setMaximum(10)
        self.uPrecision.setProperty("value", 4)
        self.uPrecision.setObjectName("uPrecision")
        self.horizontalLayout_2.addWidget(self.uPrecision)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_2.addWidget(self.label_14)
        self.uTrimZeroes = QtWidgets.QCheckBox(self.groupBox_3)
        self.uTrimZeroes.setText("")
        self.uTrimZeroes.setObjectName("uTrimZeroes")
        self.horizontalLayout_2.addWidget(self.uTrimZeroes)
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.uLabelUnits = QtWidgets.QLineEdit(self.groupBox_3)
        self.uLabelUnits.setObjectName("uLabelUnits")
        self.horizontalLayout_2.addWidget(self.uLabelUnits)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.uApplyColors = QtWidgets.QCheckBox(self.groupBox_3)
        self.uApplyColors.setText("")
        self.uApplyColors.setObjectName("uApplyColors")
        self.horizontalLayout_4.addWidget(self.uApplyColors)
        self.uColorRamp = gui.QgsColorRampButton(self.groupBox_3)
        self.uColorRamp.setObjectName("uColorRamp")
        self.horizontalLayout_4.addWidget(self.uColorRamp)
        self.uReverseRamp = QtWidgets.QCheckBox(self.groupBox_3)
        self.uReverseRamp.setObjectName("uReverseRamp")
        self.horizontalLayout_4.addWidget(self.uReverseRamp)
        self.horizontalLayout_4.setStretch(1, 1)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.gridLayout_4.addLayout(self.formLayout, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 2, 0, 1, 2)
        self.gridLayout_3.setRowStretch(1, 1)
        self.label_3.setBuddy(self.uLayerName)
        self.label_2.setBuddy(self.uThinPoints)
        self.label_11.setBuddy(self.uThinRadius)
        self.uUseGridLabel.setBuddy(self.uUseGrid)
        self.label.setBuddy(self.uLevelsNumber)
        self.label_5.setBuddy(self.uMinContour)
        self.label_6.setBuddy(self.uMaxContour)
        self.label_10.setBuddy(self.uExtend)
        self.label_7.setBuddy(self.uMethod)
        self.label_8.setBuddy(self.uOutputName)
        self.label_12.setBuddy(self.uLabelUnits)
        self.label_9.setBuddy(self.uPrecision)

        self.retranslateUi(ContourDialog)
        self.uButtonBox.accepted.connect(ContourDialog.accept)
        self.uButtonBox.rejected.connect(ContourDialog.close)
        QtCore.QMetaObject.connectSlotsByName(ContourDialog)
        ContourDialog.setTabOrder(self.uLayerName, self.uSelectedOnly)
        ContourDialog.setTabOrder(self.uSelectedOnly, self.uThinPoints)
        ContourDialog.setTabOrder(self.uThinPoints, self.uThinRadius)
        ContourDialog.setTabOrder(self.uThinRadius, self.uUseGrid)
        ContourDialog.setTabOrder(self.uUseGrid, self.uLinesContours)
        ContourDialog.setTabOrder(self.uLinesContours, self.uFilledContours)
        ContourDialog.setTabOrder(self.uFilledContours, self.uBoth)
        ContourDialog.setTabOrder(self.uBoth, self.uLayerContours)
        ContourDialog.setTabOrder(self.uLayerContours, self.uLevelsNumber)
        ContourDialog.setTabOrder(self.uLevelsNumber, self.uMinContour)
        ContourDialog.setTabOrder(self.uMinContour, self.uMaxContour)
        ContourDialog.setTabOrder(self.uMaxContour, self.uExtend)
        ContourDialog.setTabOrder(self.uExtend, self.uMethod)
        ContourDialog.setTabOrder(self.uMethod, self.uLevelsList)
        ContourDialog.setTabOrder(self.uLevelsList, self.uOutputName)
        ContourDialog.setTabOrder(self.uOutputName, self.uPrecision)
        ContourDialog.setTabOrder(self.uPrecision, self.uTrimZeroes)
        ContourDialog.setTabOrder(self.uTrimZeroes, self.uLabelUnits)
        ContourDialog.setTabOrder(self.uLabelUnits, self.uApplyColors)
        ContourDialog.setTabOrder(self.uApplyColors, self.uColorRamp)
        ContourDialog.setTabOrder(self.uColorRamp, self.uReverseRamp)
        ContourDialog.setTabOrder(self.uReverseRamp, self.uButtonBox)

    def retranslateUi(self, ContourDialog):
        _translate = QtCore.QCoreApplication.translate
        ContourDialog.setWindowTitle(_translate("ContourDialog", "Contour"))
        self.groupBox_2.setTitle(_translate("ContourDialog", "Input"))
        self.label_3.setText(_translate("ContourDialog", "Vector layer"))
        self.uLayerName.setToolTip(_translate("ContourDialog", "Point layer containing data to contour"))
        self.label_4.setText(_translate("ContourDialog", "Data field   "))
        self.uSelectedOnly.setText(_translate("ContourDialog", "Use selected points only"))
        self.label_2.setText(_translate("ContourDialog", "Apply point thinning"))
        self.label_11.setText(_translate("ContourDialog", "Radius"))
        self.uUseGridLabel.setText(_translate("ContourDialog", "Use grid based contouring"))
        self.groupBox.setTitle(_translate("ContourDialog", "Contouring"))
        self.uLinesContours.setText(_translate("ContourDialog", "contour lines"))
        self.uFilledContours.setText(_translate("ContourDialog", "filled contours"))
        self.uBoth.setText(_translate("ContourDialog", "both"))
        self.uLayerContours.setText(_translate("ContourDialog", "filled layers"))
        self.label.setText(_translate("ContourDialog", "Number"))
        self.uLevelsNumber.setStatusTip(_translate("ContourDialog", "Number of levels between min and max value (from data field)"))
        self.label_5.setText(_translate("ContourDialog", "Min"))
        self.label_6.setText(_translate("ContourDialog", "Max"))
        self.label_10.setText(_translate("ContourDialog", "Extend"))
        self.uExtend.setItemText(0, _translate("ContourDialog", "neither"))
        self.uExtend.setItemText(1, _translate("ContourDialog", "min"))
        self.uExtend.setItemText(2, _translate("ContourDialog", "max"))
        self.uExtend.setItemText(3, _translate("ContourDialog", "both"))
        self.label_7.setText(_translate("ContourDialog", "Method"))
        self.uMethod.setItemText(0, _translate("ContourDialog", "Equal"))
        self.uMethod.setItemText(1, _translate("ContourDialog", "Quantile"))
        self.uMethod.setItemText(2, _translate("ContourDialog", "Manual"))
        self.groupBox_3.setTitle(_translate("ContourDialog", "Output"))
        self.label_8.setText(_translate("ContourDialog", "Layer name"))
        self.uPrecision.setStatusTip(_translate("ContourDialog", "Number of decimal places shown in labels"))
        self.label_14.setText(_translate("ContourDialog", "Trim zeroes"))
        self.label_12.setText(_translate("ContourDialog", "Units"))
        self.label_9.setText(_translate("ContourDialog", "Label precision"))
        self.uReverseRamp.setText(_translate("ContourDialog", "reverse"))
        self.label_13.setText(_translate("ContourDialog", "Apply colors"))

from qgis import gui
